In [1]:
dict = {'Name': 'Sude', 'Age': '22', 'Class' : 'Doctorate'}
print("Name:", dict['Name'])

Name: Sude


In [3]:
dict = {'Name': 'Sude', 'Age': '22', 'Class' : 'Doctorate'}
dict['School'] = "University"
print("School:", dict["School"])

School: University


In [ ]:
#del komutu ile silme işlemi yapabiliriz.

In [4]:
phonebook = {'Sude' : '555-444', 'Buse' : '555-3333', 'Sule' : '555-2222'}
for key, value in phonebook.items():
    print(key, value, sep=' --> ')

Sude --> 555-444
Buse --> 555-3333
Sule --> 555-2222


In [9]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [10]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [11]:
type(list1)

list

In [25]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [26]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [28]:
np.repeat(10,5)

array([10, 10, 10, 10, 10])

In [29]:
arr1 = np.arange(1,20)
arr1[arr1 %2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [30]:
np.linspace(10,20,4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [31]:
np.linspace(10,50,10)

array([10.        , 14.44444444, 18.88888889, 23.33333333, 27.77777778,
       32.22222222, 36.66666667, 41.11111111, 45.55555556, 50.        ])

In [32]:
np.random.random(5)

array([0.61102351, 0.72244338, 0.32295891, 0.36178866, 0.22826323])

In [33]:
np.random.seed((123))
np.random.randint(0,100,20)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47, 73, 32, 46, 96, 25, 83, 78,
       36, 96, 80])

In [34]:
#Random.seed() kullanarak her seferinde aynı rasgele sayıyı üretmeye yarar.

In [35]:
a1 = np.random.uniform(5, 10, size = (8))
a1

array([8.68997703, 5.91245865, 5.87725878, 7.65775687, 7.65913794,
       8.17200479, 9.24715897, 8.62227662])

In [37]:
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10
(10,) 11
(11,) 12
(12,) 13
(13,) 14
(14,) 15
(15,) 16
(16,) 17
(17,) 18
(18,) 19


In [43]:
arr2 = np.arange(1,20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [44]:
arr2.sum()

190

In [45]:
#Return the cumulative sum of the elements along a given axis --> np.cumsum
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190])

In [47]:
rep2 = np.where(arr2 == 10, 99, arr2)
print(rep2)

[ 1  2  3  4  5  6  7  8  9 99 11 12 13 14 15 16 17 18 19]


In [48]:
a = np.zeros(20).reshape(2, -1)
b = np.repeat(1, 20).reshape(2, -1)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [49]:
np.vstack([a,b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [50]:
np.hstack([a,b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [51]:
c1 = np.array([10,20,30,40,50,60])
c2 = np.array([12,20,33,40,55,60])

np.intersect1d(c1, c2)

array([20, 40, 60])

In [52]:
np.setdiff1d(c1,c2)

array([10, 30, 50])

In [53]:
a = np.array([1,2,3,6,8])
b = np.array([10,2,30,60,8])

np.where(a == b)

(array([1, 4]),)

In [54]:
a1 = np.arange(0, 60)
a1[np.where((a1 > 20 ) & (a1 < 35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [55]:
a1 = np.arange(0, 60)
a1[np.where(np.logical_and(a1 > 20, a1 < 35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])