In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30,40,50,60,70])
a

array([10, 20, 30, 40, 50, 60, 70])

In [3]:
np.isin(a, [11,20])

array([False,  True, False, False, False, False, False])

In [4]:
a4 = np.arange(10,30)
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [5]:
a4[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [6]:
np.flip(a4)

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [8]:
a3 = np.array([[3,2,8,1], [70,50,10,67], [45,25,75,15], [12,9,77,4]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15],
       [12,  9, 77,  4]])

In [9]:
np.sort(a3, axis = 0)

array([[ 3,  2,  8,  1],
       [12,  9, 10,  4],
       [45, 25, 75, 15],
       [70, 50, 77, 67]])

In [10]:
np.sort(a3, axis = 1)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75],
       [ 4,  9, 12, 77]])

In [13]:
p = np.arange(0, 50)
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [14]:
np.random.shuffle(p)
p

array([12, 22, 39, 45, 48, 26, 47, 40, 18,  7, 14, 23, 42,  9, 29, 28, 49,
       35, 38, 30, 15, 46,  8,  6,  3, 21, 25, 11, 41, 37, 19, 31,  2, 43,
       16, 34, 24,  1,  5, 17, 44, 32, 20, 33,  0, 27, 13, 36, 10,  4])

In [15]:
n = 5
p[np.argsort(p)[-n:]]

array([45, 46, 47, 48, 49])

In [16]:
p[np.argpartition(-p, n)[:n]]

array([47, 48, 46, 45, 49])

In [17]:
np.set_printoptions(precision = 4)
a = np.array([12.654398765, 90.7864098354674])
a

array([12.6544, 90.7864])

In [18]:
np.set_printoptions(threshold = 3)
np.arange(0,121).reshape(11, -1)

array([[  0,   1,   2, ...,   8,   9,  10],
       [ 11,  12,  13, ...,  19,  20,  21],
       [ 22,  23,  24, ...,  30,  31,  32],
       ...,
       [ 88,  89,  90, ...,  96,  97,  98],
       [ 99, 100, 101, ..., 107, 108, 109],
       [110, 111, 112, ..., 118, 119, 120]])

In [19]:
#Vektör Toplama
v1 = np.array([1,2])
v2 = np.array([3,4])
v3 = v1 + v2
#OR
v3 = np.add(v1, v2)
print('V3 = ', v3)

V3 =  [4 6]


In [20]:
#Dot Product 
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

dotp = a1@a2
print('Dot product - ', dotp)

dotp = np.dot(a1, a2)
print('Dot product using np.dot - ', dotp)

dotp = np.inner(a1, a2)
print('Dot product using np.inner - ', dotp)

dotp = sum(np.multiply(a1, a2))
print("Dot product using np.multiply & sum - ", dotp)

dotp = np.matmul(a1, a2)
print("Dot product using np.matmul - ", dotp)

dotp = 0
for i in range(len(a1)):
    dotp = dotp + a1[i]*a2[i]
print("Dot product using for loop - ", dotp)

Dot product -  32
Dot product using np.dot -  32
Dot product using np.inner -  32
Dot product using np.multiply & sum -  32
Dot product using np.matmul -  32
Dot product using for loop -  32


In [21]:
#Vektörün uzunluğu (length)
v3 = np.array([1,2,3,4,5,6])
length = np.sqrt(np.dot(v3, v3))
length

9.539392014169456