In [1]:
import numpy as np

In [2]:
mat1 = np.random.randint(0, 500, (10,10))
print(mat1)

[[309 145 213  15 319 371 149 169 195 106]
 [228 422 171 186 204 459 480 120 308 409]
 [396 415 330 428 214 273 327 317 100 426]
 [320 359 413  72 347 384 152  67  72 343]
 [226 377 103 347   9 418 101 403   1 383]
 [307 168 307 217  77 352 409 288 150  16]
 [427 350 262 271 484 166 292 481 137 494]
 [206  15 322 210 307 153 287 155 454 286]
 [ 72 420 105  61 355 239 263  35 276 154]
 [496  61 345 144 433  64 405 403 284  40]]


In [3]:
mat1[0,0]

309

In [4]:
mat1[mat1 > 250]

array([309, 319, 371, 422, 459, 480, 308, 409, 396, 415, 330, 428, 273,
       327, 317, 426, 320, 359, 413, 347, 384, 343, 377, 347, 418, 403,
       383, 307, 307, 352, 409, 288, 427, 350, 262, 271, 484, 292, 481,
       494, 322, 307, 287, 454, 286, 420, 355, 263, 276, 496, 345, 433,
       405, 403, 284])

In [6]:
I = np.eye(9)
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [7]:
D = np.diag([1,2,3,4,5,6,7,8,9])
D

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [8]:
M = np.random.randn(5, 5)
U = np.triu(M)
L = np.tril(M)
print(M)
print('\n')
print(U)
print('\n')
print(L)

[[ 0.89843351  0.74206858  0.49916545  0.80959264 -1.38447227]
 [ 1.92922386 -2.92243315 -0.23464     2.26218358  0.48265981]
 [ 0.53104659 -1.22911939  1.75887524  0.28106613  0.51149216]
 [ 0.88256982  0.76632527 -0.01631581  0.57637482 -0.46829485]
 [-0.22795836  0.52589421 -0.44647061  0.17700108  1.64439398]]


[[ 0.89843351  0.74206858  0.49916545  0.80959264 -1.38447227]
 [ 0.         -2.92243315 -0.23464     2.26218358  0.48265981]
 [ 0.          0.          1.75887524  0.28106613  0.51149216]
 [ 0.          0.          0.          0.57637482 -0.46829485]
 [ 0.          0.          0.          0.          1.64439398]]


[[ 0.89843351  0.          0.          0.          0.        ]
 [ 1.92922386 -2.92243315  0.          0.          0.        ]
 [ 0.53104659 -1.22911939  1.75887524  0.          0.        ]
 [ 0.88256982  0.76632527 -0.01631581  0.57637482  0.        ]
 [-0.22795836  0.52589421 -0.44647061  0.17700108  1.64439398]]


In [9]:
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [10]:
A.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [11]:
A.ravel() 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [13]:
#Transpoze
M = np.array([[1,2,3], [4,-3,6], [7,8,0]])
print('Matrix(M) => \n', M)
print('\n')
print('Transpose of M => \n', np.transpose(M))
print('\n')
#OR
print(M.T)

Matrix(M) => 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]


Transpose of M => 
 [[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]


[[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]


In [14]:
#Determinant
M = np.array([[1,2,3], [4,-3,6], [7,8,0]])
print(np.linalg.det(M))

195.0


In [15]:
#Rank
M = np.array([[1,2,3], [4,-3,6], [7,8,0]])
print(np.linalg.matrix_rank(M))

3


In [16]:
#Ters Alma
M = np.array([[1,2,3], [4,-3,6], [7,8,0]])
print(np.linalg.inv(M))

[[-0.24615385  0.12307692  0.10769231]
 [ 0.21538462 -0.10769231  0.03076923]
 [ 0.27179487  0.03076923 -0.05641026]]


In [17]:
#Matrislerin Kuvveti
M1 = np.array([[1,2], [4,5]])
M1

array([[1, 2],
       [4, 5]])

In [18]:
M1@M1@M1

array([[ 57,  78],
       [156, 213]])

In [20]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [21]:
v = np.array([1,2,3,4,5,6,7])
s1 = pd.Series(v)
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [22]:
s1.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
s1

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64

In [23]:
v2 = np.random.random(10)
ind2 = np.arange(0, 10)
s = pd.Series(v2, ind2)
v2, ind2, s

(array([0.81927846, 0.81479512, 0.3975765 , 0.4399872 , 0.74191891,
        0.70353391, 0.259029  , 0.65619364, 0.92942012, 0.21828554]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 0    0.819278
 1    0.814795
 2    0.397577
 3    0.439987
 4    0.741919
 5    0.703534
 6    0.259029
 7    0.656194
 8    0.929420
 9    0.218286
 dtype: float64)

In [24]:
dict1 = {'a1' : 10, 'a2' : 20, 'a3' : 30, 'a4' : 40}
s3 = pd.Series(dict1)
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [28]:
s3.drop('a4', inplace = False)

a1    10
a2    20
a3    30
dtype: int64

In [31]:
s3 = s3.append(pd.Series({'a5' : 7}))
s3

a1    10
a2    20
a3    30
a4    40
a5     7
dtype: int64